import type { Portfolio, UserProfile } from './types';

export interface SampleScenario {
   profile: UserProfile;
   portfolio: Portfolio;
}

const currentYear = new Date().getFullYear();

export const sampleScenarios: Record<string, SampleScenario> = {
   'Moderate Couple': {
      profile: { primaryName: 'Pat', spouseName: 'Chris' },
      portfolio: {
         config: {
            current_age_primary: 65,
            current_age_spouse: 61,
            simulation_years: 30,
            start_year: currentYear,
            annual_spend_net: 65000,
            inflation_rate: 0.03,
            conservative_growth: false,
            strategy_target: 'irmaa_tier_1',
            spending_strategy: 'fixed_dollar',
            withdrawal_rate: 0.04,
            guardrails_config: {
               initial_withdrawal_rate: 0.05,
               floor_percent: 0.8,
               ceiling_percent: 1.2,
               adjustment_percent: 0.1,
            },
            tax_brackets_federal: [],
            tax_rate_state: 0.05,
            irmaa_limit_tier_1: 206000,
            social_security: {
               primary_benefit: 36000,
               primary_start_age: 67,
               spouse_benefit: 26400,
               spouse_start_age: 67,
            },
            rmd_start_age: 73,
            planned_expenses: [
               {
                  name: 'New car',
                  amount: 10000,
                  expense_type: 'one_time',
                  year: currentYear + 5,
                  inflation_adjusted: false,
               },
            ],
            income_streams: [
               {
                  name: 'Pension',
                  kind: 'pension',
                  amount: 22000,
                  start_age: 65,
                  end_age: null,
                  taxable_pct: 1.0,
                  cola_rate: 0.02,
                  owner: 'primary',
                  pretax_401k: 0,
                  roth_401k: 0,
               },
            ],
            ss_auto: {
               primary_fra_amount: 36000,
               primary_start_age: 67,
               spouse_fra_amount: 26400,
               spouse_start_age: 67,
               fra_age: 67,
               cola_rate: 0.025,
            },
            salary_auto: null,
            retirement_age: 65,
            excess_income_routing: 'brokerage',
            withdrawal_order: ['cash', 'brokerage', 'pretax', 'roth'],
         },
         accounts: [
            {
               id: 'mod_401k_p',
               name: '401(k)',
               balance: 300000,
               type: '401k',
               owner: 'primary',
               cost_basis_ratio: 0.0,
               available_at_age: 60,
            },
            {
               id: 'mod_cash',
               name: 'Cash/CD',
               balance: 20000,
               type: 'cash_cd',
               owner: 'primary',
               cost_basis_ratio: 1.0,
               available_at_age: 0,
            },
            {
               id: 'mod_ira_s',
               name: 'IRA - Spouse',
               balance: 50000,
               type: 'ira',
               owner: 'spouse',
               cost_basis_ratio: 0.0,
               available_at_age: 60,
            },
         ],
      },
   },
   'Comfortable Single': {
      profile: { primaryName: 'Jordan', spouseName: '' },
      portfolio: {
         config: {
            current_age_primary: 63,
            current_age_spouse: 0,
            simulation_years: 32,
            start_year: currentYear,
            annual_spend_net: 85000,
            inflation_rate: 0.03,
            conservative_growth: false,
            strategy_target: 'irmaa_tier_1',
            spending_strategy: 'fixed_dollar',
            withdrawal_rate: 0.04,
            guardrails_config: {
               initial_withdrawal_rate: 0.05,
               floor_percent: 0.8,
               ceiling_percent: 1.2,
               adjustment_percent: 0.1,
            },
            tax_brackets_federal: [],
            tax_rate_state: 0.05,
            irmaa_limit_tier_1: 206000,
            social_security: {
               primary_benefit: 36000,
               primary_start_age: 67,
               spouse_benefit: 0,
               spouse_start_age: 67,
            },
            rmd_start_age: 73,
            planned_expenses: [
               {
                  name: 'Vacation home',
                  amount: 100000,
                  expense_type: 'one_time',
                  year: currentYear + 5,
                  inflation_adjusted: false,
               },
            ],
            income_streams: [
               {
                  name: '__salary_primary',
                  kind: 'employment',
                  amount: 140000,
                  start_age: 63,
                  end_age: 66,
                  taxable_pct: 1.0,
                  cola_rate: 0.03,
                  owner: 'primary',
                  pretax_401k: 23500,
                  roth_401k: 0,
               },
               {
                  name: 'Alimony',
                  kind: 'alimony',
                  amount: 18000,
                  start_age: 63,
                  end_age: null,
                  taxable_pct: 1.0,
                  cola_rate: null,
                  owner: 'primary',
                  pretax_401k: 0,
                  roth_401k: 0,
               },
               {
                  name: 'Rental income',
                  kind: 'rental',
                  amount: 52500,
                  start_age: 63,
                  end_age: null,
                  taxable_pct: 1.0,
                  cola_rate: 0.02,
                  owner: 'primary',
                  pretax_401k: 0,
                  roth_401k: 0,
               },
            ],
            ss_auto: {
               primary_fra_amount: 36000,
               primary_start_age: 67,
               spouse_fra_amount: null,
               spouse_start_age: null,
               fra_age: 67,
               cola_rate: 0.025,
            },
            salary_auto: {
               primary_salary: 140000,
               primary_growth: 0.03,
               primary_end_age: null,
               spouse_salary: null,
               spouse_growth: null,
               spouse_end_age: null,
               primary_pretax_401k: 23500,
               primary_roth_401k: 0,
               spouse_pretax_401k: 0,
               spouse_roth_401k: 0,
            },
            retirement_age: 67,
            excess_income_routing: 'brokerage',
            withdrawal_order: ['cash', 'brokerage', 'pretax', 'roth'],
         },
         accounts: [
            {
               id: 'comf_401k',
               name: '401(k)',
               balance: 950000,
               type: '401k',
               owner: 'primary',
               cost_basis_ratio: 0.0,
               available_at_age: 60,
            },
            {
               id: 'comf_ira',
               name: 'IRA',
               balance: 100000,
               type: 'ira',
               owner: 'primary',
               cost_basis_ratio: 0.0,
               available_at_age: 60,
            },
            {
               id: 'comf_brokerage',
               name: 'Brokerage',
               balance: 250000,
               type: 'brokerage',
               owner: 'primary',
               cost_basis_ratio: 0.4,
               available_at_age: 0,
               stock_pct: 70,
            },
         ],
      },
   },
   'Wealthier Couple': {
      profile: { primaryName: 'Alex', spouseName: 'Sam' },
      portfolio: {
         config: {
            current_age_primary: 65,
            current_age_spouse: 58,
            simulation_years: 30,
            start_year: currentYear,
            annual_spend_net: 115000,
            inflation_rate: 0.03,
            conservative_growth: false,
            strategy_target: '22_percent_bracket',
            spending_strategy: 'fixed_dollar',
            withdrawal_rate: 0.04,
            guardrails_config: {
               initial_withdrawal_rate: 0.05,
               floor_percent: 0.8,
               ceiling_percent: 1.2,
               adjustment_percent: 0.1,
            },
            tax_brackets_federal: [],
            tax_rate_state: 0.05,
            irmaa_limit_tier_1: 206000,
            social_security: {
               primary_benefit: 3500,
               primary_start_age: 70,
               spouse_benefit: 2000,
               spouse_start_age: 65,
            },
            rmd_start_age: 73,
            planned_expenses: [
               {
                  name: 'Managed Care',
                  amount: 150000,
                  expense_type: 'recurring',
                  inflation_adjusted: true,
                  start_year: 2032,
                  end_year: 2038,
               },
               {
                  name: 'New Car',
                  amount: 28000,
                  expense_type: 'one_time',
                  year: 2029,
                  inflation_adjusted: true,
               },
            ],
            income_streams: [],
            ss_auto: {
               primary_fra_amount: 3500,
               primary_start_age: 70,
               spouse_fra_amount: 2000,
               spouse_start_age: 65,
               fra_age: 67,
               cola_rate: 0.025,
            },
            salary_auto: null,
            retirement_age: null,
            excess_income_routing: 'brokerage',
            withdrawal_order: ['cash', 'brokerage', 'pretax', 'roth'],
         },
         accounts: [
            {
               id: 'wlth_roth_p',
               name: 'Alex-WF-RothIRA',
               balance: 48000,
               type: 'roth_ira',
               owner: 'primary',
               cost_basis_ratio: 1.0,
               available_at_age: 60,
               stock_pct: 89,
            },
            {
               id: 'wlth_brok_p1',
               name: 'Alex-WF-JointInvestment',
               balance: 658000,
               type: 'brokerage',
               owner: 'primary',
               cost_basis_ratio: 0.4,
               available_at_age: 0,
               stock_pct: 95,
            },
            {
               id: 'wlth_ira_p',
               name: 'Alex-WF-IRA',
               balance: 318000,
               type: 'ira',
               owner: 'primary',
               cost_basis_ratio: 0.0,
               available_at_age: 60,
               stock_pct: 84,
            },
            {
               id: 'wlth_brok_p2',
               name: 'Alex-Vanguard-Investment',
               balance: 183000,
               type: 'brokerage',
               owner: 'primary',
               cost_basis_ratio: 0.4,
               available_at_age: 0,
               stock_pct: 97,
            },
            {
               id: 'wlth_401k_p',
               name: 'Alex-Leidos-Empower-401K',
               balance: 1012000,
               type: '401k',
               owner: 'primary',
               cost_basis_ratio: 0.0,
               available_at_age: 60,
               stock_pct: 0,
            },
            {
               id: 'wlth_roth_s',
               name: 'Sam-WF-RothIRA',
               balance: 162000,
               type: 'roth_ira',
               owner: 'spouse',
               cost_basis_ratio: 1.0,
               available_at_age: 60,
               stock_pct: 89,
            },
            {
               id: 'wlth_ira_s1',
               name: 'Sam-WF-IRA',
               balance: 294000,
               type: 'ira',
               owner: 'spouse',
               cost_basis_ratio: 0.0,
               available_at_age: 60,
               stock_pct: 90,
            },
            {
               id: 'wlth_ira_s2',
               name: 'Sam-WF-IRA-401k',
               balance: 751000,
               type: 'ira',
               owner: 'spouse',
               cost_basis_ratio: 0.0,
               available_at_age: 60,
               stock_pct: 89,
            },
         ],
      },
   },
};

export const samplePortfolio: Portfolio =
   sampleScenarios['Moderate Couple'].portfolio;
export const sampleProfile: UserProfile =
   sampleScenarios['Moderate Couple'].profile;
